/**
 * Message contract between the content scripts and the service worker.
 *
 * WHY THIS IS A SEPARATE MODULE
 * -----------------------------
 * The contract used to live inside `auditor.ts`, which registers a
 * `chrome.runtime.onMessage` listener as a side effect of being imported. That
 * made the message names untestable and unshareable: any consumer that imported
 * them in order to check a name was silently forced to also stand up a service
 * worker listener, which fails outside a browser.
 *
 * Keeping the contract here means both sides can import it with no side effects,
 * and a renamed message becomes a compile error in both places at once instead of
 * a runtime "unknown message type" that fails closed and looks like a dead
 * feature rather than a broken contract.
 *
 * @module background/message-types
 */

export const MESSAGE_TYPES = {
  /* AiTM / trust */
  VALIDATE_DOMAIN: "VALIDATE_DOMAIN",
  GET_TRUST_STATUS: "GET_TRUST_STATUS",
  REPORT_ANOMALY: "REPORT_ANOMALY",

  /* Vault session */
  UNLOCK_VAULT: "UNLOCK_VAULT",
  LOCK_VAULT: "LOCK_VAULT",
  CHECK_VAULT_STATUS: "CHECK_VAULT_STATUS",

  /* Local encryption (session key held by the worker) */
  ENCRYPT_DATA: "ENCRYPT_DATA",
  DECRYPT_DATA: "DECRYPT_DATA",

  /* Plus authorization */
  REQUEST_MANAGED_CAPABILITY: "REQUEST_MANAGED_CAPABILITY",
  REQUEST_RELEASE_SHARE: "REQUEST_RELEASE_SHARE",
  GET_PLUS_PUBLIC_KEY: "GET_PLUS_PUBLIC_KEY",

  /* Credential release — the guarded path to a form field */
  LIST_CREDENTIALS_FOR_ORIGIN: "LIST_CREDENTIALS_FOR_ORIGIN",
  RELEASE_CREDENTIAL: "RELEASE_CREDENTIAL",

  /* Credential authoring — the write side of the same store */
  AUTHOR_CREDENTIAL: "AUTHOR_CREDENTIAL",

  /* Step-up (third factor) — CHALLENGE_REQUIRED follow-up */
  START_STEP_UP: "START_STEP_UP",
  /**
   * R3: the user approves a release. There is no PIN — the old PIN was
   * generated by `createChallenge` and never delivered to anyone, so the flow
   * could not be completed. The background obtains Core's signed approval and
   * forwards it to Plus, which verifies it and issues the capability.
   */
  APPROVE_STEP_UP: "APPROVE_STEP_UP",
  GET_PENDING_STEP_UP: "GET_PENDING_STEP_UP",
} as const;

export type MessageType = (typeof MESSAGE_TYPES)[keyof typeof MESSAGE_TYPES];

/* ------------------------------------------------------------------ */
/*  Payloads                                                           */
/* ------------------------------------------------------------------ */

export interface ValidateDomainMessage {
  type: typeof MESSAGE_TYPES.VALIDATE_DOMAIN;
  hostname: string;
  expectedDomain: string;
  tabId?: number;
}

export interface GetTrustStatusMessage {
  type: typeof MESSAGE_TYPES.GET_TRUST_STATUS;
  domain: string;
}

export interface ReportAnomalyMessage {
  type: typeof MESSAGE_TYPES.REPORT_ANOMALY;
  domain: string;
  anomalyType: string;
  severity: "low" | "medium" | "high";
  details: string;
}

export interface UnlockVaultMessage {
  type: typeof MESSAGE_TYPES.UNLOCK_VAULT;
  vaultId: string;
  passphrase?: string;
}

export interface LockVaultMessage {
  type: typeof MESSAGE_TYPES.LOCK_VAULT;
}

export interface CheckVaultStatusMessage {
  type: typeof MESSAGE_TYPES.CHECK_VAULT_STATUS;
}

export interface EncryptDataMessage {
  type: typeof MESSAGE_TYPES.ENCRYPT_DATA;
  payload: string;
}

export interface DecryptDataMessage {
  type: typeof MESSAGE_TYPES.DECRYPT_DATA;
  payload: string;
}

export interface RequestManagedCapabilityMessage {
  type: typeof MESSAGE_TYPES.REQUEST_MANAGED_CAPABILITY;
  payload: {
    userId: string;
    resourceId: string;
    operation: "AUTOFILL" | "VIEW" | "TOTP";
    secretRef: string;
    deviceId?: string;
    assurance: 1 | 2 | 3;
    context?: {
      country?: string;
      ip?: string;
      userAgent?: string;
      timestamp?: number;
    };
  };
}

/**
 * Ask Core to release the Release Share for one managed credential.
 *
 * The payload mirrors `POST /api/v1/vaults/{vaultId}/managed-release` exactly:
 * the capability Plus issued and the credential it is for. Core pins the
 * verification key itself, so no public key may travel in the body — a key the
 * caller supplies is a key the caller chooses.
 */
export interface RequestReleaseShareMessage {
  type: typeof MESSAGE_TYPES.REQUEST_RELEASE_SHARE;
  payload: {
    capabilityToken: {
      payload: unknown;
      signature: string;
      protectedHeader: string;
    };
    /** The credential the capability was issued for; verified against the vault. */
    credentialId: string;
  };
}

export interface GetPlusPublicKeyMessage {
  type: typeof MESSAGE_TYPES.GET_PLUS_PUBLIC_KEY;
}

/** Content script asks which credentials are bound to the page's origin. */
export interface ListCredentialsForOriginMessage {
  type: typeof MESSAGE_TYPES.LIST_CREDENTIALS_FOR_ORIGIN;
  origin: string;
}

/** Content script asks for a specific credential to be released. */
export interface ReleaseCredentialMessage {
  type: typeof MESSAGE_TYPES.RELEASE_CREDENTIAL;
  credentialId: string;
  origin: string;
  operation: "AUTOFILL" | "TOTP";
  documentOrigin: string;
  topLevelOrigin: string;
  isFramed: boolean;
}

/**
 * Persist one credential into the release store while the vault is unlocked.
 *
 * Deliberately narrow: the caller may not choose the record id, the mode, or a
 * Release Share reference. Ids are minted by the worker so a caller cannot
 * overwrite another record, and client-side authoring is personal-only —
 * managed entries are created server-side, where the Release Share exists.
 */
export interface AuthorCredentialMessage {
  type: typeof MESSAGE_TYPES.AUTHOR_CREDENTIAL;
  payload: {
    /** Raw origin; canonicalized and rejected if unusable, never trusted. */
    origin: string;
    username: string;
    password: string;
    title: string;
    totpSeedBase32?: string;
  };
}

/**
 * Ask which release the worker is waiting on a step-up for.
 *
 * `START_STEP_UP` requires a binding, and the party that observed the
 * `CHALLENGE_REQUIRED` denial (the content script) is gone by the time the user
 * reaches the popup. The worker recorded the binding when it refused; this is
 * how the next leg recovers it without the caller inventing one.
 */
export interface GetPendingStepUpMessage {
  type: typeof MESSAGE_TYPES.GET_PENDING_STEP_UP;
}

/**
 * Content script starts a third-factor challenge for one exact release.
 *
 * The binding is echoed back on every subsequent call so the service worker can
 * refuse a PIN that is presented for a different credential, origin or operation
 * than the challenge was started for.
 */
export interface StartStepUpMessage {
  type: typeof MESSAGE_TYPES.START_STEP_UP;
  binding: {
    credentialId: string;
    origin: string;
    operation: "AUTOFILL" | "TOTP";
  };
}

/**
 * The user approved the release a challenge was started for.
 *
 * Carries no secret. The whole point of R3 is that the third factor is the
 * user's decision, not something they know: Core signs the decision, so this
 * message carries only the challenge to approve.
 */
export interface ApproveStepUpMessage {
  type: typeof MESSAGE_TYPES.APPROVE_STEP_UP;
  challengeId: string;
}

export type BackgroundMessage =
  | ValidateDomainMessage
  | GetTrustStatusMessage
  | ReportAnomalyMessage
  | UnlockVaultMessage
  | LockVaultMessage
  | CheckVaultStatusMessage
  | EncryptDataMessage
  | DecryptDataMessage
  | RequestManagedCapabilityMessage
  | RequestReleaseShareMessage
  | GetPlusPublicKeyMessage
  | ListCredentialsForOriginMessage
  | ReleaseCredentialMessage
  | AuthorCredentialMessage
  | StartStepUpMessage
  | ApproveStepUpMessage
  | GetPendingStepUpMessage;

export interface BackgroundResponse<T = unknown> {
  ok: boolean;
  data?: T;
  error?: string;
}
