#!/bin/bash
# Script para cargar automáticamente la extensión de CyberVault en Chrome

EXTENSION_DIR="/Users/statick/apps/cybervault/dist"

echo "📦 Cargando extensión CyberVault en Chrome..."

# Usar Apple Script para cargar la extensión
osascript << 'EOF'
tell application "Google Chrome"
    activate
    tell active tab of window 1
        set URL to "chrome://extensions"
    end tell
    delay 1
end tell
EOF

echo "✅ Chrome abierto en extensiones"
echo ""
echo "Para cargar la extensión manualmente:"
echo "1. Busca el botón 'Cargar extensión sin empaquetar'"
echo "2. Selecciona el directorio: $EXTENSION_DIR"
echo ""
echo "O usa Chrome Flags para habilitar la carga automática:"
echo "chrome://flags/#extensions-nav-autogenerated"

# Intentar cargar mediante Chrome CLI (si está habilitado)
open -a "Google Chrome" "chrome://extensions/?force_load_unpacked=$EXTENSION_DIR" 2>/dev/null || echo "No se puede cargar automáticamente. Hazlo manualmente."
